import test from 'node:test';
import assert from 'node:assert/strict';
import { blocksmithQuests, countMaterials, isInsideQuestZone, validateQuestBuild } from '../site/games/blocksmith-quests.js';
import { stepVertical } from '../site/games/blocksmith-physics.js';
import { createWorldReservations, RESOURCE_PATCHES, ROCK_CLUSTERS, TREE_SPOTS } from '../site/games/blocksmith-world-layout.js';

const blocks=(count,type='moss',start=0)=>Array.from({length:count},(_,index)=>({x:start+index,y:0,z:0,type}));
const solid=(width,depth,layers,type)=>Array.from({length:layers},(_,y)=>Array.from({length:width},(_,x)=>Array.from({length:depth},(_,z)=>({x,y,z,type})))).flat(2);
const outline=(width,depth,type)=>solid(width,depth,1,type).filter(block=>block.x===0||block.x===width-1||block.z===0||block.z===depth-1);
const towers=(heights,type)=>heights.flatMap((height,x)=>Array.from({length:height},(_,y)=>({x,y,z:0,type})));

test('Blocksmith provides twenty readable Years 3–5 maths quests',()=>{assert.equal(blocksmithQuests.length,20);assert.deepEqual([...new Set(blocksmithQuests.map(quest=>quest.year))],['Year 3','Year 4','Year 5']);assert.equal(new Set(blocksmithQuests.flatMap(quest=>Object.keys(quest.materialPlan))).size,4);blocksmithQuests.forEach(quest=>{assert.ok(quest.objectiveId);assert.ok(quest.age);assert.ok(quest.prompt.split(/\s+/).length<=24);assert.equal(Object.values(quest.materialPlan).reduce((sum,count)=>sum+count,0),quest.targetBlocks);assert.doesNotMatch(quest.prompt,/\b(?:12 moss|6 wood|4 glass|8 stone|10 and 20|12 and 24)\b/i)})});
test('half of 24 is validated from the built material mix',()=>{const quest=blocksmithQuests.find(item=>item.id==='half-24');const correct=[...blocks(12,'moss'),...blocks(12,'glass',12)];assert.equal(validateQuestBuild(quest,correct).complete,true);assert.equal(validateQuestBuild(quest,correct.slice(0,23)).difference,-1)});
test('material feedback does not reveal the hidden material counts',()=>{const quest=blocksmithQuests.find(item=>item.id==='quarter-16');const build=[...blocks(10,'wood'),...blocks(6,'glass',10)];const result=validateQuestBuild(quest,build);assert.equal(result.complete,false);assert.match(result.message,/material fractions do not match/);assert.doesNotMatch(result.message,/12 wood|4 glass/)});
test('the Year 3 array answer must use three equal rows',()=>{const quest=blocksmithQuests.find(item=>item.id==='three-rows-12');assert.equal(validateQuestBuild(quest,solid(4,3,1,'wood')).complete,true);assert.match(validateQuestBuild(quest,blocks(12,'wood')).message,/3 equal rows/)});
test('the Year 4 perimeter accepts an outline but not a filled shape',()=>{const quest=blocksmithQuests.find(item=>item.id==='perimeter-6-4');assert.equal(outline(6,4,'stone').length,16);assert.equal(validateQuestBuild(quest,outline(6,4,'stone')).complete,true);assert.equal(validateQuestBuild(quest,solid(4,4,1,'stone')).complete,false)});
test('the Year 5 volume question requires the inferred second layer',()=>{const quest=blocksmithQuests.find(item=>item.id==='volume-24');assert.equal(validateQuestBuild(quest,solid(4,3,2,'stone')).complete,true);assert.equal(validateQuestBuild(quest,solid(6,4,1,'stone')).complete,false)});
test('the Year 5 percentage question checks the inferred 4-to-16 mix',()=>{const quest=blocksmithQuests.find(item=>item.id==='percent-20');const build=[...blocks(4,'wood'),...blocks(16,'glass',4)];assert.deepEqual(countMaterials(build),{wood:4,glass:16});assert.equal(validateQuestBuild(quest,build).complete,true)});
test('fraction tower questions validate vertical height ratios',()=>{const quest=blocksmithQuests.find(item=>item.id==='third-towers-30');assert.equal(validateQuestBuild(quest,towers([10,20],'wood')).complete,true);assert.equal(validateQuestBuild(quest,towers([15,15],'wood')).complete,false)});
test('quest feedback tells the learner how many total blocks to change',()=>{const quest=blocksmithQuests.find(item=>item.id==='three-rows-12');assert.match(validateQuestBuild(quest,blocks(4,'wood')).message,/Add 8 more blocks/);assert.match(validateQuestBuild(quest,blocks(14,'wood')).message,/Remove 2 blocks/)});
test('zone boundaries include marked cells and exclude neighbours',()=>{const quest=blocksmithQuests[0];assert.equal(isInsideQuestZone(quest,quest.zone.x,quest.zone.z),true);assert.equal(isInsideQuestZone(quest,quest.zone.x+quest.zone.width-1,quest.zone.z+quest.zone.depth-1),true);assert.equal(isInsideQuestZone(quest,quest.zone.x-1,quest.zone.z),false)});
test('invalid build records are rejected',()=>{assert.throws(()=>validateQuestBuild(blocksmithQuests[0],[{x:0,y:0,type:'moss'}]),TypeError);assert.throws(()=>validateQuestBuild(null,[]),TypeError)});
test('world fixtures occupy unique grid columns',()=>{const layout=createWorldReservations(blocksmithQuests);assert.deepEqual(layout.conflicts,[]);blocksmithQuests.forEach(quest=>{assert.equal(isInsideQuestZone(quest,quest.position.x,quest.position.z),false);assert.ok(Number.isInteger(quest.position.x)&&Number.isInteger(quest.position.z))});RESOURCE_PATCHES.forEach(patch=>assert.ok(Number.isInteger(patch.origin.x)&&Number.isInteger(patch.origin.z)&&Number.isInteger(patch.sign.x)&&Number.isInteger(patch.sign.z)));TREE_SPOTS.flat().forEach(value=>assert.ok(Number.isInteger(value)));ROCK_CLUSTERS.flat(2).forEach(value=>assert.ok(Number.isInteger(value)))});
test('gravity drops a player into a one-block hole and lands them',()=>{let state={height:0,velocity:0,grounded:true,flying:false};for(let index=0;index<60;index+=1)state=stepVertical(state,{delta:1/60,supportHeight:-1});assert.equal(state.height,-1);assert.equal(state.grounded,true)});
test('jump rises before gravity returns the player to the surface',()=>{let state={height:0,velocity:5.4,grounded:false,flying:false};let peak=0;for(let index=0;index<120;index+=1){state=stepVertical(state,{delta:1/60,supportHeight:0});peak=Math.max(peak,state.height)}assert.ok(peak>.8);assert.equal(state.height,0);assert.equal(state.grounded,true)});
test('flight can rise and ignores gravity until it is disabled',()=>{const risen=stepVertical({height:2,velocity:0,grounded:false,flying:true},{delta:1,ascend:true,supportHeight:0});assert.equal(risen.height,9);assert.equal(risen.flying,true);const falling=stepVertical({...risen,flying:false},{delta:.1,supportHeight:0});assert.ok(falling.height<risen.height)});
