import test from 'node:test';
import assert from 'node:assert/strict';
import { blocksmithQuests, countMaterials, isInsideQuestZone, validateQuestBuild } from '../site/games/blocksmith-quests.js';
import { createWorldReservations, RESOURCE_PATCHES, ROCK_CLUSTERS, TREE_SPOTS } from '../site/games/blocksmith-world-layout.js';

const blocks=(count,type='moss',start=0)=>Array.from({length:count},(_,index)=>({x:start+index,y:0,z:0,type}));
const solid=(width,depth,layers,type)=>Array.from({length:layers},(_,y)=>Array.from({length:width},(_,x)=>Array.from({length:depth},(_,z)=>({x,y,z,type})))).flat(2);
const outline=(width,depth,type)=>solid(width,depth,1,type).filter(block=>block.x===0||block.x===width-1||block.z===0||block.z===depth-1);

test('Blocksmith provides a readable Years 3–5 quest progression',()=>{assert.equal(blocksmithQuests.length,6);assert.deepEqual([...new Set(blocksmithQuests.map(quest=>quest.year))],['Year 3','Year 4','Year 5']);assert.equal(new Set(blocksmithQuests.flatMap(quest=>Object.keys(quest.materialPlan))).size,4);blocksmithQuests.forEach(quest=>{assert.ok(quest.objectiveId);assert.ok(quest.age);assert.ok(quest.prompt.split(/\s+/).length<=22);assert.equal(Object.values(quest.materialPlan).reduce((sum,count)=>sum+count,0),quest.targetBlocks)})});
test('half of 24 requires twelve moss blocks',()=>{const quest=blocksmithQuests.find(item=>item.id==='half-24');assert.equal(validateQuestBuild(quest,blocks(12)).complete,true);assert.equal(validateQuestBuild(quest,blocks(11)).difference,-1);assert.equal(validateQuestBuild(quest,blocks(13)).difference,1)});
test('material feedback explains what to swap',()=>{const quest=blocksmithQuests.find(item=>item.id==='quarters-12');const build=[...blocks(10,'wood'),...blocks(2,'glass',10)];const result=validateQuestBuild(quest,build);assert.equal(result.complete,false);assert.match(result.message,/remove 1 wood/);assert.match(result.message,/add 1 glass/)});
test('the Year 3 array must be arranged as three rows of four',()=>{const quest=blocksmithQuests.find(item=>item.id==='array-12');assert.equal(validateQuestBuild(quest,solid(4,3,1,'wood')).complete,true);assert.match(validateQuestBuild(quest,blocks(12,'wood')).message,/3 rows of 4/)});
test('the Year 4 perimeter accepts an outline but not a filled shape',()=>{const quest=blocksmithQuests.find(item=>item.id==='perimeter-5-3');assert.equal(outline(5,3,'stone').length,12);assert.equal(validateQuestBuild(quest,outline(5,3,'stone')).complete,true);assert.equal(validateQuestBuild(quest,solid(4,3,1,'stone')).complete,false)});
test('the Year 5 volume quest requires two filled layers',()=>{const quest=blocksmithQuests.find(item=>item.id==='volume-12');assert.equal(validateQuestBuild(quest,solid(3,2,2,'stone')).complete,true);assert.equal(validateQuestBuild(quest,solid(4,3,1,'stone')).complete,false)});
test('the Year 5 percentage quest checks the 5-to-15 material mix',()=>{const quest=blocksmithQuests.find(item=>item.id==='percent-20');const build=[...blocks(15,'wood'),...blocks(5,'glass',15)];assert.deepEqual(countMaterials(build),{wood:15,glass:5});assert.equal(validateQuestBuild(quest,build).complete,true)});
test('quest feedback tells the learner exactly how many blocks to change',()=>{const quest=blocksmithQuests[1];assert.match(validateQuestBuild(quest,blocks(4,'wood')).message,/Add 8 more blocks/);assert.match(validateQuestBuild(quest,blocks(14,'wood')).message,/Remove 2 blocks/)});
test('zone boundaries include marked cells and exclude neighbours',()=>{const quest=blocksmithQuests[0];assert.equal(isInsideQuestZone(quest,quest.zone.x,quest.zone.z),true);assert.equal(isInsideQuestZone(quest,quest.zone.x+quest.zone.width-1,quest.zone.z+quest.zone.depth-1),true);assert.equal(isInsideQuestZone(quest,quest.zone.x-1,quest.zone.z),false)});
test('invalid build records are rejected',()=>{assert.throws(()=>validateQuestBuild(blocksmithQuests[0],[{x:0,y:0,type:'moss'}]),TypeError);assert.throws(()=>validateQuestBuild(null,[]),TypeError)});
test('world fixtures occupy unique grid columns',()=>{const layout=createWorldReservations(blocksmithQuests);assert.deepEqual(layout.conflicts,[]);blocksmithQuests.forEach(quest=>{assert.equal(isInsideQuestZone(quest,quest.position.x,quest.position.z),false);assert.ok(Number.isInteger(quest.position.x)&&Number.isInteger(quest.position.z))});RESOURCE_PATCHES.forEach(patch=>assert.ok(Number.isInteger(patch.origin.x)&&Number.isInteger(patch.origin.z)&&Number.isInteger(patch.sign.x)&&Number.isInteger(patch.sign.z)));TREE_SPOTS.flat().forEach(value=>assert.ok(Number.isInteger(value)));ROCK_CLUSTERS.flat(2).forEach(value=>assert.ok(Number.isInteger(value)))});
