import test from 'node:test';
import assert from 'node:assert/strict';
import { curriculumQuestionBank, CURRICULUM_BANK_COUNTS, CURRICULUM_SUBJECTS, CURRICULUM_YEARS, getCurriculumQuestions, validateCurriculumQuestionBank } from '../site/games/curriculum-question-bank.js';
import { createInfiniteQuestionSet, createLevelQuestionSet, generateCurriculumQuestion, validateGeneratedQuestion } from '../site/games/curriculum-question-generator.js';

test('the deep curriculum bank contains 900 validated questions',()=>{assert.equal(validateCurriculumQuestionBank(),true);assert.equal(curriculumQuestionBank.length,900);assert.deepEqual(CURRICULUM_BANK_COUNTS,{total:900,perYear:300,perYearSubject:100,maths:300,science:300,english:300})});
test('every year and subject has 100 questions split evenly across five levels',()=>{for(const year of CURRICULUM_YEARS)for(const subject of CURRICULUM_SUBJECTS){const bank=getCurriculumQuestions({year,subject});assert.equal(bank.length,100,`Year ${year} ${subject}`);for(let level=1;level<=5;level+=1)assert.equal(getCurriculumQuestions({year,subject,level}).length,20,`Year ${year} ${subject} level ${level}`)}});
test('every question is compact, answerable and supported for game play',()=>{for(const question of curriculumQuestionBank){assert.ok(question.prompt.length>=12&&question.prompt.length<=150);assert.ok(question.hint.length>=10);assert.equal(question.learn.title,`Learn: ${question.strand}`);assert.ok(question.learn.text.length>45);assert.equal(question.learn.steps.length,3);assert.match(question.learn.example,/^Worked example:/);assert.ok(question.learn.check.length>25);if(question.type==='choice'){assert.equal(question.options.length,4);assert.ok(question.options.includes(question.answer));assert.equal(new Set(question.options).size,4);assert.ok(question.options.every(option=>option.length<=110))}else{assert.equal(question.type,'spell');assert.equal([...question.answer].sort().join(''),[...question.letters].sort().join(''));assert.equal(question.prompt.toLocaleLowerCase('en-GB').includes(question.answer),false)}}});
test('generated questions are deterministic and remain inside the selected year',()=>{for(const year of CURRICULUM_YEARS)for(const subject of CURRICULUM_SUBJECTS)for(let set=0;set<12;set+=1){const first=createInfiniteQuestionSet({subject,year,set}),second=createInfiniteQuestionSet({subject,year,set});assert.deepEqual(first,second);assert.deepEqual(first.map(question=>question.level),[1,2,3,4,5]);assert.ok(first.every(question=>question.yearNumber===year&&validateGeneratedQuestion(question)))}});
test('direct generation rejects unsupported years and scopes valid results',()=>{assert.throws(()=>generateCurriculumQuestion({subject:'maths',year:2,level:1}),/year must be 3, 4 or 5/i);for(const year of CURRICULUM_YEARS)for(const subject of CURRICULUM_SUBJECTS){const question=generateCurriculumQuestion({subject,year,level:3,seed:17});assert.equal(question.yearNumber,year);assert.equal(question.subject,subject);assert.equal(question.level,3)}});
test('a 25-wall world never repeats a visible question',()=>{for(const year of CURRICULUM_YEARS)for(const subject of CURRICULUM_SUBJECTS)for(let set=0;set<80;set+=1){const questions=Array.from({length:5},(_,index)=>createLevelQuestionSet({subject,year,level:index+1,set,count:5})).flat(),prompts=questions.map(question=>question.prompt.trim().toLocaleLowerCase('en-GB'));assert.equal(new Set(prompts).size,25,`Year ${year} ${subject} set ${set}`)}});
test('four consecutive worlds exhaust 100 source questions without repetition',()=>{for(const year of CURRICULUM_YEARS)for(const subject of CURRICULUM_SUBJECTS){const sourceIds=[];for(let set=0;set<4;set+=1)for(let level=1;level<=5;level+=1)sourceIds.push(...createLevelQuestionSet({subject,year,level,set,count:5}).map(question=>question.sourceId));assert.equal(sourceIds.length,100);assert.equal(new Set(sourceIds).size,100,`Year ${year} ${subject}`)}});
test('every adjacent question set draws a disjoint source batch',()=>{for(const year of CURRICULUM_YEARS)for(const subject of CURRICULUM_SUBJECTS)for(let set=0;set<12;set+=1){const first=new Set(Array.from({length:5},(_,index)=>createLevelQuestionSet({subject,year,level:index+1,set,count:5})).flat().map(question=>question.sourceId)),second=Array.from({length:5},(_,index)=>createLevelQuestionSet({subject,year,level:index+1,set:set+1,count:5})).flat();assert.equal(second.some(question=>first.has(question.sourceId)),false,`Year ${year} ${subject} sets ${set}/${set+1}`)}});
