import test from 'node:test';
import assert from 'node:assert/strict';
import { curriculumQuestionBank, CURRICULUM_BANK_COUNTS, getCurriculumQuestions, validateCurriculumQuestionBank } from '../site/games/curriculum-question-bank.js';
import { createInfiniteQuestionSet, createLevelQuestionSet, generateCurriculumQuestion, validateGeneratedQuestion } from '../site/games/curriculum-question-generator.js';

test('the curriculum bank contains 150 validated questions',()=>{assert.equal(validateCurriculumQuestionBank(),true);assert.equal(curriculumQuestionBank.length,150);assert.deepEqual(Object.fromEntries(['maths','science','english'].map(subject=>[subject,getCurriculumQuestions({subject}).length])),{maths:50,science:50,english:50});assert.deepEqual(CURRICULUM_BANK_COUNTS,{total:150,maths:50,science:50,english:50})});
test('each subject has ten reviewed questions at every progressive level',()=>{for(const subject of ['maths','science','english']){const questions=getCurriculumQuestions({subject});assert.deepEqual(new Set(questions.map(question=>question.level)),new Set([1,2,3,4,5]));assert.deepEqual(new Set(questions.map(question=>question.year)),new Set(['Year 3','Year 4','Year 5']));for(let level=1;level<=5;level+=1)assert.equal(getCurriculumQuestions({subject,level}).length,10)}});
test('Learn support is detailed and tailored to the question topic',()=>{assert.ok(new Set(curriculumQuestionBank.map(question=>question.learn.text)).size>=80);for(const question of curriculumQuestionBank){assert.equal(question.learn.title,`Learn: ${question.strand}`);assert.ok(question.learn.text.length>55);assert.equal(question.learn.steps.length,3);assert.ok(question.learn.steps.every(step=>step.length>25));assert.match(question.learn.example,/^Worked example:/);assert.ok(question.learn.check.length>25)}});
test('generated sets are deterministic, supported and answerable',()=>{for(const subject of ['maths','science','english'])for(let set=0;set<40;set+=1){const first=createInfiniteQuestionSet({subject,set}),second=createInfiniteQuestionSet({subject,set});assert.deepEqual(first,second);assert.deepEqual(first.map(question=>question.level),[1,2,3,4,5]);assert.ok(first.every(validateGeneratedQuestion))}});
test('maths generators produce fresh numeric variants without changing difficulty',()=>{const variants=Array.from({length:30},(_,seed)=>generateCurriculumQuestion({subject:'maths',level:5,seed}));assert.ok(new Set(variants.map(question=>question.prompt)).size>20);assert.ok(variants.every(question=>question.year==='Year 5'&&question.level===5&&question.options.includes(question.answer)))});
test('every generated game level contains five deterministic questions at one difficulty',()=>{for(const subject of ['maths','science','english'])for(let level=1;level<=5;level+=1){const first=createLevelQuestionSet({subject,level,set:12,count:5}),second=createLevelQuestionSet({subject,level,set:12,count:5});assert.equal(first.length,5);assert.deepEqual(first,second);assert.ok(first.every(question=>question.level===level&&validateGeneratedQuestion(question)));assert.equal(new Set(first.map(question=>question.id)).size,5)}});
test('a 25-wall world never repeats a visible question',()=>{for(const subject of ['maths','science','english'])for(let set=0;set<500;set+=1){const questions=Array.from({length:5},(_,index)=>createLevelQuestionSet({subject,level:index+1,set,count:5})).flat(),prompts=questions.map(question=>question.prompt.trim().toLocaleLowerCase('en-GB'));assert.equal(new Set(prompts).size,25,`${subject} set ${set} repeated a prompt`)}});
test('every consecutive question set draws non-overlapping reviewed source items',()=>{for(const subject of ['maths','science','english'])for(let set=0;set<20;set++){const first=new Set(Array.from({length:5},(_,index)=>createLevelQuestionSet({subject,level:index+1,set,count:5})).flat().map(question=>question.sourceId)),second=Array.from({length:5},(_,index)=>createLevelQuestionSet({subject,level:index+1,set:set+1,count:5})).flat();assert.equal(second.some(question=>first.has(question.sourceId)),false,`${subject} sets ${set} and ${set+1} reused source items`)}});
