import test from 'node:test';
import assert from 'node:assert/strict';
import { curriculumQuestionBank, CURRICULUM_BANK_COUNTS, getCurriculumQuestions, validateCurriculumQuestionBank } from '../site/games/curriculum-question-bank.js';
import { createInfiniteQuestionSet, generateCurriculumQuestion, validateGeneratedQuestion } from '../site/games/curriculum-question-generator.js';

test('the curriculum bank contains exactly 100 validated questions',()=>{assert.equal(validateCurriculumQuestionBank(),true);assert.equal(curriculumQuestionBank.length,100);assert.deepEqual(Object.fromEntries(['maths','science','english'].map(subject=>[subject,getCurriculumQuestions({subject}).length])),{maths:34,science:33,english:33});assert.deepEqual(CURRICULUM_BANK_COUNTS,{total:100,maths:34,science:33,english:33})});
test('each subject progresses through five levels and Years 3 to 5',()=>{for(const subject of ['maths','science','english']){const questions=getCurriculumQuestions({subject});assert.deepEqual(new Set(questions.map(question=>question.level)),new Set([1,2,3,4,5]));assert.deepEqual(new Set(questions.map(question=>question.year)),new Set(['Year 3','Year 4','Year 5']))}});
test('generated sets are deterministic, supported and answerable',()=>{for(const subject of ['maths','science','english'])for(let set=0;set<40;set+=1){const first=createInfiniteQuestionSet({subject,set}),second=createInfiniteQuestionSet({subject,set});assert.deepEqual(first,second);assert.deepEqual(first.map(question=>question.level),[1,2,3,4,5]);assert.ok(first.every(validateGeneratedQuestion))}});
test('maths generators produce fresh numeric variants without changing difficulty',()=>{const variants=Array.from({length:30},(_,seed)=>generateCurriculumQuestion({subject:'maths',level:5,seed}));assert.ok(new Set(variants.map(question=>question.prompt)).size>20);assert.ok(variants.every(question=>question.year==='Year 5'&&question.level===5&&question.options.includes(question.answer)))});
