import test from 'node:test';
import assert from 'node:assert/strict';
import { ONEBLOCK_BLOCK_IDS, ONEBLOCK_PHASE_GOAL, ONEBLOCK_PHASES, answerOneBlockChallenge, createOneBlockRun, deserializeOneBlockRun, mineOneBlock, oneBlockMaterialAt, returnOneBlockInventory, serializeOneBlockRun, spendOneBlockInventory } from '../site/games/oneblock-engine.js';

test('One Block Academy has ten original weighted resource phases',()=>{assert.equal(ONEBLOCK_PHASES.length,10);assert.equal(new Set(ONEBLOCK_PHASES.map(phase=>phase.id)).size,10);for(const phase of ONEBLOCK_PHASES){assert.ok(phase.blocks.length>=3);assert.ok(phase.blocks.every(([id,weight])=>ONEBLOCK_BLOCK_IDS.includes(id)&&weight>0))}});
test('renewable block sequences are deterministic and phase-scoped',()=>{const first=Array.from({length:30},(_,totalMined)=>oneBlockMaterialAt({phaseIndex:0,totalMined,seed:42})),again=Array.from({length:30},(_,totalMined)=>oneBlockMaterialAt({phaseIndex:0,totalMined,seed:42})),frost=Array.from({length:30},(_,totalMined)=>oneBlockMaterialAt({phaseIndex:2,totalMined,seed:42}));assert.deepEqual(first,again);assert.notDeepEqual(first,frost);assert.ok(first.every(id=>['moss','earth','wood'].includes(id)));assert.ok(frost.every(id=>['ice','glass','stone'].includes(id)))});
test('mining grants the visible block and locks exactly at the phase gate',()=>{let run=createOneBlockRun({seed:7});for(let index=0;index<ONEBLOCK_PHASE_GOAL;index+=1){const visible=run.currentBlock,result=mineOneBlock(run);run=result.state;assert.equal(run.inventory[visible]>=1,true)}assert.equal(run.challengePending,true);assert.equal(run.minedInPhase,ONEBLOCK_PHASE_GOAL);const locked=mineOneBlock(run);assert.equal(locked.state,run);assert.equal(locked.event.kind,'locked')});
test('a wrong answer preserves the island phase and a correct answer upgrades it',()=>{let run=createOneBlockRun({seed:9,minedInPhase:ONEBLOCK_PHASE_GOAL,challengePending:true});const wrong=answerOneBlockChallenge(run,{selected:'12',answer:'13'});assert.equal(wrong.event.kind,'incorrect');assert.equal(wrong.state.phaseIndex,0);assert.equal(wrong.state.challengePending,true);const right=answerOneBlockChallenge(wrong.state,{selected:'13',answer:'13'});assert.equal(right.event.kind,'advanced');assert.equal(right.state.phaseIndex,1);assert.equal(right.state.challengePending,false);assert.equal(right.state.inventory.stone,2)});
test('all ten gates open an infinite afterglow without repeating a gate',()=>{let run=createOneBlockRun({seed:11});for(let phase=0;phase<ONEBLOCK_PHASES.length;phase+=1){run=createOneBlockRun({...run,minedInPhase:ONEBLOCK_PHASE_GOAL,challengePending:true});run=answerOneBlockChallenge(run,{selected:'yes',answer:'yes'}).state}assert.equal(run.phaseIndex,ONEBLOCK_PHASES.length);assert.equal(run.completed,true);assert.equal(run.challengePending,false);for(let count=0;count<35;count+=1)run=mineOneBlock(run).state;assert.equal(run.challengePending,false);assert.equal(run.totalMined,35)});
test('inventory spending, returns and save restoration stay bounded',()=>{let run=createOneBlockRun({inventory:{wood:3,stone:-4,unknown:99}});assert.equal(run.inventory.wood,3);assert.equal(run.inventory.stone,0);let result=spendOneBlockInventory(run,'wood',2);assert.equal(result.spent,true);run=result.state;assert.equal(run.inventory.wood,1);assert.equal(spendOneBlockInventory(run,'wood',2).spent,false);run=returnOneBlockInventory(run,'wood',2);assert.equal(run.inventory.wood,3);assert.deepEqual(deserializeOneBlockRun(serializeOneBlockRun(run)),run);assert.equal(deserializeOneBlockRun('{bad json').phaseIndex,0)});
