import test from 'node:test';
import assert from 'node:assert/strict';
import { createOutbreakRounds, validateOutbreakRounds } from '../site/games/outbreak-questions.js';
import { canOccupyOutbreakWorld, findOutbreakPath, isOutbreakLowClearance, outbreakCheckpoints, outbreakMapPlan, outbreakTileToWorld } from '../site/games/outbreak-map.js';
import { confirmOutbreakCount, createOutbreakRun, createOutbreakSwarm, currentOutbreakRound, damageOutbreakPlayer, eliminateOutbreakZombie, isOutbreakPlayerHidden, killOutbreakAgent, reachOutbreakCheckpoint, respawnOutbreakPlayer, stepOutbreakSwarm } from '../site/games/outbreak-engine.js';

test('every year produces five bounded curriculum equations for swarm play',()=>{for(const year of[3,4,5])for(let set=0;set<100;set+=1){const rounds=createOutbreakRounds({year,set});assert.equal(validateOutbreakRounds(rounds,{year}),true);assert.deepEqual(rounds.map(round=>round.level),[1,2,3,4,5]);rounds.forEach(round=>{assert.equal(round.target,round.answer);assert.ok(round.target>=3&&round.target<=15);assert.equal(round.swarmSize,round.target+4);assert.ok(round.learn.text.length>25);assert.equal(round.learn.steps.length,3)})}});
test('Gridlock Courtyard is a tiled original map with reachable checkpoint circuits',()=>{assert.equal(outbreakMapPlan.size,32);assert.equal(outbreakMapPlan.tileSize,2);assert.equal(outbreakMapPlan.checkpoints.length,6);assert.ok(outbreakMapPlan.cells.wall.length>100);assert.ok(outbreakMapPlan.cells.cover.length>=10);assert.ok(outbreakMapPlan.cells.low.length>=10);for(let index=0;index<outbreakCheckpoints.length-1;index+=1)assert.ok(findOutbreakPath(outbreakCheckpoints[index].tile,outbreakCheckpoints[index+1].tile).length>1)});
test('standing players cannot enter crouch tunnels but crouched players can',()=>{const cell=outbreakMapPlan.cells.low[0],world=outbreakTileToWorld(cell);assert.equal(isOutbreakLowClearance(cell.x,cell.z),true);assert.equal(canOccupyOutbreakWorld(world,{crouched:false}),false);assert.equal(canOccupyOutbreakWorld(world,{crouched:true}),true)});
test('the run hides the answer and requires an exact confirmed count before the next checkpoint',()=>{const rounds=createOutbreakRounds({year:4,set:2});let run=createOutbreakRun(rounds);assert.equal(run.phase,'hunt');run=eliminateOutbreakZombie(run);run=confirmOutbreakCount(run);assert.equal(run.phase,'hunt');assert.equal(run.eliminated,0);assert.match(run.feedback,/Not quite/);for(let count=0;count<currentOutbreakRound(run).target;count+=1)run=eliminateOutbreakZombie(run);assert.equal(run.phase,'hunt');run=confirmOutbreakCount(run);assert.equal(run.phase,'checkpoint');assert.equal(reachOutbreakCheckpoint(run,2).checkpointIndex,0);run=reachOutbreakCheckpoint(run,1);assert.equal(run.levelIndex,1);assert.equal(run.phase,'hunt');assert.equal(run.eliminated,0)});
test('all five confirmed equations and checkpoints complete the operation',()=>{let run=createOutbreakRun(createOutbreakRounds({year:5,set:7}));for(let level=0;level<5;level+=1){for(let count=0;count<currentOutbreakRound(run).target;count+=1)run=eliminateOutbreakZombie(run);run=confirmOutbreakCount(run);run=reachOutbreakCheckpoint(run,level+1)}assert.equal(run.complete,true);assert.equal(run.phase,'complete');assert.equal(run.checkpointIndex,5)});
test('player damage resets only the current equation at the last checkpoint',()=>{let run=createOutbreakRun(createOutbreakRounds({year:3}));run={...run,health:8,eliminated:2};run=damageOutbreakPlayer(run,10);assert.equal(run.phase,'down');run=respawnOutbreakPlayer(run);assert.equal(run.phase,'hunt');assert.equal(run.health,100);assert.equal(run.eliminated,0);assert.equal(run.deaths,1);assert.equal(run.checkpointIndex,0)});
test('swarms are deterministic, bounded and preserve pooled slots when killed',()=>{const round=createOutbreakRounds({year:3})[0],first=createOutbreakSwarm(round),second=createOutbreakSwarm(round);assert.deepEqual(first,second);assert.equal(first.length,round.swarmSize);assert.ok(first.every(agent=>canOccupyOutbreakWorld(agent,{radius:.34,crouched:true})));const killed=killOutbreakAgent(first,0);assert.equal(killed.killed,true);assert.equal(killed.agents.length,first.length);assert.equal(killed.agents[0].alive,false);assert.equal(killOutbreakAgent(killed.agents,0).killed,false)});
test('zombies chase deterministically while hidden crouched players break pursuit',()=>{const round=createOutbreakRounds({year:4})[0],agents=createOutbreakSwarm(round),player={x:agents[0].x+3,z:agents[0].z};const visible=stepOutbreakSwarm(agents,{player,delta:.1,hidden:false}),hidden=stepOutbreakSwarm(agents,{player,delta:.1,hidden:true});assert.deepEqual(visible,stepOutbreakSwarm(agents,{player,delta:.1,hidden:false}));assert.notDeepEqual(visible[0],hidden[0]);const coverWorld=outbreakTileToWorld(outbreakMapPlan.cells.cover[0]);assert.equal(isOutbreakPlayerHidden(coverWorld,false),false);assert.equal(isOutbreakPlayerHidden(coverWorld,true),true)});
