import test from 'node:test';
import assert from 'node:assert/strict';
import { chooseSkyboundLane, createSkyboundRun, getSkyboundMovementAxes, getSkyboundStage, reachSkyboundCheckpoint, respawnSkyboundStage, SKYBOUND_LANES } from '../site/games/skybound-engine.js';
import { skyboundQuestions, validateSkyboundQuestions } from '../site/games/skybound-questions.js';

function correctLane(state,question){return SKYBOUND_LANES.find(lane=>state.laneAnswers[lane]===question.answer)}
function wrongLane(state,question){return SKYBOUND_LANES.find(lane=>state.laneAnswers[lane]!==question.answer)}

test('Skybound provides ten supported maths bridges for Years 3–5',()=>{assert.equal(validateSkyboundQuestions(),true);assert.equal(skyboundQuestions.length,10);assert.deepEqual(new Set(skyboundQuestions.map(question=>question.year)),new Set(['Year 3','Year 4','Year 5']));skyboundQuestions.forEach(question=>{assert.equal(question.options.length,2);assert.ok(question.options.includes(question.answer));assert.ok(question.hint.length>10);assert.ok(question.learn.text.length>30);assert.ok(question.learn.example.length>15);assert.ok(question.prompt.split(/\s+/).length<=22)})});
test('each bridge deterministically maps its two options to left and right glass',()=>{const first=createSkyboundRun(skyboundQuestions),second=createSkyboundRun(skyboundQuestions);assert.deepEqual(first.laneAnswers,second.laneAnswers);assert.deepEqual(new Set(Object.values(first.laneAnswers)),new Set(skyboundQuestions[0].options));assert.equal(getSkyboundStage(first,skyboundQuestions),skyboundQuestions[0])});
test('a wrong glass tile falls and retries from the same checkpoint',()=>{const initial=createSkyboundRun(skyboundQuestions),lane=wrongLane(initial,skyboundQuestions[0]),fallen=chooseSkyboundLane(initial,skyboundQuestions,lane);assert.equal(fallen.status,'falling');assert.equal(fallen.brokenLane,lane);assert.equal(fallen.checkpointStage,0);const retried=respawnSkyboundStage(fallen);assert.equal(retried.status,'ready');assert.equal(retried.stageIndex,0);assert.equal(retried.checkpointStage,0);assert.equal(retried.attempt,2);assert.deepEqual(retried.laneAnswers,initial.laneAnswers)});
test('falling after a safe choice also restores the current bridge question',()=>{const initial=createSkyboundRun(skyboundQuestions),crossing=chooseSkyboundLane(initial,skyboundQuestions,correctLane(initial,skyboundQuestions[0])),retried=respawnSkyboundStage(crossing);assert.equal(retried.status,'ready');assert.equal(retried.stageIndex,0);assert.equal(retried.attempt,2);assert.equal(retried.selectedLane,null)});
test('a correct tile unlocks only the next checkpoint',()=>{const initial=createSkyboundRun(skyboundQuestions),lane=correctLane(initial,skyboundQuestions[0]),crossing=chooseSkyboundLane(initial,skyboundQuestions,lane);assert.equal(crossing.status,'crossing');assert.equal(reachSkyboundCheckpoint(initial,skyboundQuestions),initial);const advanced=reachSkyboundCheckpoint(crossing,skyboundQuestions);assert.equal(advanced.stageIndex,1);assert.equal(advanced.checkpointStage,1);assert.equal(advanced.status,'ready');assert.equal(advanced.attempt,1)});
test('crossing all ten bridges completes the run',()=>{let state=createSkyboundRun(skyboundQuestions);for(const question of skyboundQuestions){state=chooseSkyboundLane(state,skyboundQuestions,correctLane(state,question));state=reachSkyboundCheckpoint(state,skyboundQuestions)}assert.equal(state.completed,true);assert.equal(state.status,'complete');assert.equal(state.checkpointStage,skyboundQuestions.length)});
test('lane choices are ignored after the bridge has been answered',()=>{const initial=createSkyboundRun(skyboundQuestions),first=chooseSkyboundLane(initial,skyboundQuestions,correctLane(initial,skyboundQuestions[0]));assert.equal(chooseSkyboundLane(first,skyboundQuestions,'left'),first);assert.throws(()=>chooseSkyboundLane(initial,skyboundQuestions,'middle'),TypeError)});
test('camera-relative left and right match what the player sees',()=>{assert.deepEqual(getSkyboundMovementAxes({left:true}),{x:1,z:0});assert.deepEqual(getSkyboundMovementAxes({right:true}),{x:-1,z:0});assert.deepEqual(getSkyboundMovementAxes({forward:true}),{x:0,z:1});const diagonal=getSkyboundMovementAxes({right:true,forward:true});assert.ok(Math.abs(Math.hypot(diagonal.x,diagonal.z)-1)<Number.EPSILON)});
test('movement rotates with the orbit camera',()=>{const quarterTurn=getSkyboundMovementAxes({forward:true},Math.PI/2),right=getSkyboundMovementAxes({right:true},Math.PI/2);assert.ok(Math.abs(quarterTurn.x+1)<Number.EPSILON);assert.ok(Math.abs(quarterTurn.z)<1e-12);assert.ok(Math.abs(right.x)<1e-12);assert.ok(Math.abs(right.z+1)<Number.EPSILON)});
