import test from 'node:test';
import assert from 'node:assert/strict';
import { chooseSkyboundLane, createSkyboundJumpControl, createSkyboundRun, getSkyboundJoystickVector, getSkyboundMovementAxes, getSkyboundStage, isSkyboundFootprintOnSupport, queueSkyboundJump, reachSkyboundCheckpoint, respawnSkyboundStage, SKYBOUND_LANES, SKYBOUND_PLAYER_FOOT_RADIUS, stepSkyboundJump } from '../site/games/skybound-engine.js';
import { skyboundQuestions, validateSkyboundQuestions } from '../site/games/skybound-questions.js';

function correctLane(state,question){return SKYBOUND_LANES.find(lane=>state.laneAnswers[lane]===question.answer)}
function wrongLane(state,question){return SKYBOUND_LANES.find(lane=>state.laneAnswers[lane]!==question.answer)}

test('Skybound provides ten supported maths bridges for Years 3–5',()=>{assert.equal(validateSkyboundQuestions(),true);assert.equal(skyboundQuestions.length,10);assert.deepEqual(new Set(skyboundQuestions.map(question=>question.year)),new Set(['Year 3','Year 4','Year 5']));skyboundQuestions.forEach(question=>{assert.equal(question.options.length,2);assert.ok(question.options.includes(question.answer));assert.ok(question.hint.length>10);assert.ok(question.learn.text.length>30);assert.ok(question.learn.example.length>15);assert.ok(question.prompt.split(/\s+/).length<=22)})});
test('each bridge deterministically maps its two options to left and right glass',()=>{const first=createSkyboundRun(skyboundQuestions),second=createSkyboundRun(skyboundQuestions);assert.deepEqual(first.laneAnswers,second.laneAnswers);assert.deepEqual(new Set(Object.values(first.laneAnswers)),new Set(skyboundQuestions[0].options));assert.equal(getSkyboundStage(first,skyboundQuestions),skyboundQuestions[0])});
test('a wrong glass tile falls and retries from the same checkpoint',()=>{const initial=createSkyboundRun(skyboundQuestions),lane=wrongLane(initial,skyboundQuestions[0]),fallen=chooseSkyboundLane(initial,skyboundQuestions,lane);assert.equal(fallen.status,'falling');assert.equal(fallen.brokenLane,lane);assert.equal(fallen.checkpointStage,0);const retried=respawnSkyboundStage(fallen);assert.equal(retried.status,'ready');assert.equal(retried.stageIndex,0);assert.equal(retried.checkpointStage,0);assert.equal(retried.attempt,2);assert.deepEqual(retried.laneAnswers,initial.laneAnswers)});
test('falling after a safe choice also restores the current bridge question',()=>{const initial=createSkyboundRun(skyboundQuestions),crossing=chooseSkyboundLane(initial,skyboundQuestions,correctLane(initial,skyboundQuestions[0])),retried=respawnSkyboundStage(crossing);assert.equal(retried.status,'ready');assert.equal(retried.stageIndex,0);assert.equal(retried.attempt,2);assert.equal(retried.selectedLane,null)});
test('a correct tile unlocks only the next checkpoint',()=>{const initial=createSkyboundRun(skyboundQuestions),lane=correctLane(initial,skyboundQuestions[0]),crossing=chooseSkyboundLane(initial,skyboundQuestions,lane);assert.equal(crossing.status,'crossing');assert.equal(reachSkyboundCheckpoint(initial,skyboundQuestions),initial);const advanced=reachSkyboundCheckpoint(crossing,skyboundQuestions);assert.equal(advanced.stageIndex,1);assert.equal(advanced.checkpointStage,1);assert.equal(advanced.status,'ready');assert.equal(advanced.attempt,1)});
test('crossing all ten bridges completes the run',()=>{let state=createSkyboundRun(skyboundQuestions);for(const question of skyboundQuestions){state=chooseSkyboundLane(state,skyboundQuestions,correctLane(state,question));state=reachSkyboundCheckpoint(state,skyboundQuestions)}assert.equal(state.completed,true);assert.equal(state.status,'complete');assert.equal(state.checkpointStage,skyboundQuestions.length)});
test('lane choices are ignored after the bridge has been answered',()=>{const initial=createSkyboundRun(skyboundQuestions),first=chooseSkyboundLane(initial,skyboundQuestions,correctLane(initial,skyboundQuestions[0]));assert.equal(chooseSkyboundLane(first,skyboundQuestions,'left'),first);assert.throws(()=>chooseSkyboundLane(initial,skyboundQuestions,'middle'),TypeError)});
test('camera-relative left and right match what the player sees',()=>{assert.deepEqual(getSkyboundMovementAxes({left:true}),{x:1,z:0});assert.deepEqual(getSkyboundMovementAxes({right:true}),{x:-1,z:0});assert.deepEqual(getSkyboundMovementAxes({forward:true}),{x:0,z:1});const diagonal=getSkyboundMovementAxes({right:true,forward:true});assert.ok(Math.abs(Math.hypot(diagonal.x,diagonal.z)-1)<Number.EPSILON)});
test('movement rotates with the orbit camera',()=>{const quarterTurn=getSkyboundMovementAxes({forward:true},Math.PI/2),right=getSkyboundMovementAxes({right:true},Math.PI/2);assert.ok(Math.abs(quarterTurn.x+1)<Number.EPSILON);assert.ok(Math.abs(quarterTurn.z)<1e-12);assert.ok(Math.abs(right.x)<1e-12);assert.ok(Math.abs(right.z+1)<Number.EPSILON)});
test('jump presses can be buffered and repeated after landing',()=>{let control=queueSkyboundJump(createSkyboundJumpControl()),step=stepSkyboundJump(control,{delta:1/60,grounded:true});assert.equal(step.jumped,true);control=queueSkyboundJump(step.state);step=stepSkyboundJump(control,{delta:.1,grounded:false});assert.equal(step.jumped,false);step=stepSkyboundJump(step.state,{delta:.05,grounded:true});assert.equal(step.jumped,true);control=queueSkyboundJump(step.state);step=stepSkyboundJump(control,{delta:1/60,grounded:true});assert.equal(step.jumped,true)});
test('analogue stick provides 360-degree variable-speed movement',()=>{const bounds={left:0,top:0,width:100,height:100},centre=getSkyboundJoystickVector(50,50,bounds),half=getSkyboundJoystickVector(64.5,50,bounds),edge=getSkyboundJoystickVector(100,0,bounds);assert.deepEqual(centre,{x:0,y:0,knobX:0,knobY:0});assert.ok(Math.abs(half.x-.5)<1e-12);assert.equal(half.y,0);assert.ok(Math.abs(Math.hypot(edge.x,edge.y)-1)<Number.EPSILON);const movement=getSkyboundMovementAxes({moveX:.5,moveY:.5});assert.ok(Math.abs(movement.x+.5)<1e-12);assert.ok(Math.abs(movement.z-.5)<1e-12)});
test('the avatar can land across every visible tile edge without bridging the answer gap',()=>{const left={x:-1.75,z:6,width:2.8,depth:3,solid:true},right={...left,x:1.75};assert.equal(SKYBOUND_PLAYER_FOOT_RADIUS,.3);for(const [x,z] of[[-3.15,6],[-.35,6],[-1.75,4.5],[-1.75,7.5],[-3.44,6],[-.06,6]])assert.equal(isSkyboundFootprintOnSupport(x,z,left),true,`expected ${x},${z} on left tile`);assert.equal(isSkyboundFootprintOnSupport(-3.46,6,left),false);assert.equal(isSkyboundFootprintOnSupport(-3.4,4.25,left),false,'a foot beyond both corner edges must not land');assert.equal(isSkyboundFootprintOnSupport(0,6,left),false);assert.equal(isSkyboundFootprintOnSupport(0,6,right),false);assert.equal(isSkyboundFootprintOnSupport(-1.75,6,{...left,solid:false}),false)});
