import test from 'node:test';
import assert from 'node:assert/strict';
import { createWordwallRun, createWordwallShareData, getWordwallChallenge, getWordwallSpiralPose, isWordwallFootprintOnSupport, reachWordwallCheckpoint, resolveWordwallGateMovement, respawnWordwallRun, submitWordwallAnswer, WORDWALL_GATE_COLLIDER, WORDWALL_SPIRAL } from '../site/games/wordwall-engine.js';
import { validateWordwallChallenges, wordwallChallenges } from '../site/games/wordwall-challenges.js';

test('LexiClimb provides six curriculum-linked English gates for Years 3–5',()=>{assert.equal(validateWordwallChallenges(),true);assert.equal(wordwallChallenges.length,6);assert.deepEqual(new Set(wordwallChallenges.map(item=>item.year)),new Set(['Year 3','Year 4','Year 5']));for(const challenge of wordwallChallenges){assert.match(challenge.objectiveId,/^ENG-/);assert.ok(challenge.hint.length>15);assert.ok(challenge.learn.text.length>35);assert.ok(challenge.learn.example.length>10)}});
test('spelling gates contain exactly the letters needed by their answer',()=>{for(const challenge of wordwallChallenges.filter(item=>item.type==='spell'))assert.equal([...challenge.letters].sort().join(''),[...challenge.answer].sort().join(''))});
test('the next checkpoint opens only its matching English gate',()=>{const initial=createWordwallRun(wordwallChallenges);assert.equal(reachWordwallCheckpoint(initial,wordwallChallenges,2),initial);const reached=reachWordwallCheckpoint(initial,wordwallChallenges,1);assert.equal(reached.status,'challenge');assert.equal(reached.checkpointIndex,1);assert.equal(getWordwallChallenge(reached,wordwallChallenges),wordwallChallenges[0])});
test('an incorrect answer keeps the wall closed and preserves the checkpoint',()=>{const reached=reachWordwallCheckpoint(createWordwallRun(wordwallChallenges),wordwallChallenges,1),result=submitWordwallAnswer(reached,wordwallChallenges,'a');assert.equal(result.correct,false);assert.equal(result.state.status,'challenge');assert.equal(result.state.solvedCount,0);assert.equal(result.state.checkpointIndex,1);assert.equal(result.state.attempts,2)});
test('a correct answer unlocks one wall and permits the next course',()=>{const reached=reachWordwallCheckpoint(createWordwallRun(wordwallChallenges),wordwallChallenges,1),result=submitWordwallAnswer(reached,wordwallChallenges,'E');assert.equal(result.correct,true);assert.equal(result.state.status,'running');assert.equal(result.state.solvedCount,1);assert.equal(result.state.checkpointIndex,1);assert.equal(result.state.activeChallenge,null)});
test('falling returns to the reached checkpoint without solving its wall',()=>{const reached=reachWordwallCheckpoint(createWordwallRun(wordwallChallenges),wordwallChallenges,1),respawned=respawnWordwallRun(reached);assert.equal(respawned.checkpointIndex,1);assert.equal(respawned.solvedCount,0);assert.equal(respawned.status,'running')});
test('six courses rise through one and a half turns around the tower',()=>{const checkpoints=Array.from({length:7},(_,index)=>getWordwallSpiralPose(index));for(let index=0;index<checkpoints.length;index+=1){const checkpoint=checkpoints[index];assert.ok(Math.abs(Math.hypot(checkpoint.x,checkpoint.z)-WORDWALL_SPIRAL.radius)<1e-12);assert.equal(checkpoint.top,index*WORDWALL_SPIRAL.stageRise);if(index)assert.ok(Math.abs(checkpoint.angle-checkpoints[index-1].angle-WORDWALL_SPIRAL.stageArc)<1e-12)}assert.ok(Math.abs(checkpoints[0].x)<1e-12);assert.equal(checkpoints[0].z,-WORDWALL_SPIRAL.radius);assert.ok(Math.abs(checkpoints[6].x)<1e-11);assert.equal(Math.round(checkpoints[6].z),WORDWALL_SPIRAL.radius)});
test('rotated spiral platforms use their visible local footprint',()=>{const pose=getWordwallSpiralPose(2),support={...pose,width:7,depth:6,solid:true};assert.equal(isWordwallFootprintOnSupport(pose.x+pose.radialX*3.8,pose.z+pose.radialZ*3.8,support),true);assert.equal(isWordwallFootprintOnSupport(pose.x+pose.radialX*3.81,pose.z+pose.radialZ*3.81,support),false);assert.equal(isWordwallFootprintOnSupport(pose.x+pose.forwardX*3.3,pose.z+pose.forwardZ*3.3,support),true);assert.equal(isWordwallFootprintOnSupport(pose.x+pose.forwardX*3.31,pose.z+pose.forwardZ*3.31,support),false)});
test('a closed word wall is solid from its front, back, sides and edges',()=>{const gate={x:0,z:32.1,bottom:4,...WORDWALL_GATE_COLLIDER,open:false},move=(overrides)=>resolveWordwallGateMovement({previousX:0,previousZ:31.3,nextX:0,nextZ:31.6,playerY:4,...overrides},gate);assert.deepEqual(move({}),{x:0,z:31.3,blockedX:false,blockedZ:true});assert.deepEqual(move({previousZ:32.9,nextZ:32.6}),{x:0,z:32.9,blockedX:false,blockedZ:true});assert.deepEqual(move({previousX:3.9,nextX:3.7,previousZ:32.1,nextZ:32.1}),{x:3.9,z:32.1,blockedX:true,blockedZ:false});assert.equal(move({previousX:3.9,nextX:3.9,previousZ:31.3,nextZ:31.6}).blockedZ,false,'the player may deliberately go around only after leaving the platform-width collider');assert.equal(resolveWordwallGateMovement({previousX:0,previousZ:31.3,nextX:0,nextZ:31.6,playerY:7.16},gate).blockedZ,false,'feet above the bricks may cross');assert.equal(resolveWordwallGateMovement({previousX:0,previousZ:31.3,nextX:0,nextZ:31.6,playerY:4},{...gate,open:true}).blockedZ,false,'an unlocked wall no longer collides')});
test('word walls remain solid after rotating around the spiral',()=>{const gate={x:-2.1,z:13,bottom:8,yaw:-Math.PI/2,...WORDWALL_GATE_COLLIDER,open:false},resolved=resolveWordwallGateMovement({previousX:-1.3,previousZ:13,nextX:-1.6,nextZ:13,playerY:8},gate);assert.ok(Math.abs(resolved.x+1.3)<1e-12);assert.ok(Math.abs(resolved.z-13)<1e-12);assert.equal(resolved.blockedX,true)});
test('solving all six gates completes the tower',()=>{let state=createWordwallRun(wordwallChallenges);for(let index=0;index<wordwallChallenges.length;index+=1){state=reachWordwallCheckpoint(state,wordwallChallenges,index+1);const result=submitWordwallAnswer(state,wordwallChallenges,wordwallChallenges[index].answer);assert.equal(result.correct,true);state=result.state}assert.equal(state.completed,true);assert.equal(state.status,'complete');assert.equal(state.solvedCount,6)});
test('completion sharing strips debug state and exposes no learner data',()=>{assert.deepEqual(createWordwallShareData('https://example.test/games/wordwall.html?preview=challenge#gate'),{title:'LexiClimb Tower achievement',text:'I completed all 6 English gates in LexiClimb Tower on EduGames!',url:'https://example.test/games/wordwall.html'})});
